package com.routespring.dto;

public enum BIllingInfoDescTypes {
	BILLING_INFO_DESC_TYPE_PERSONAL_CARD,
	BILLING_INFO_DESC_TYPE_PRE_PAYMENT,
	BILLING_INFO_DESC_TYPE_CORP_CARD,
	BILLING_INFO_DESC_TYPE_DIRECT_BILLING

}
